Added wordnet from jar functionality (unpacking from jar to temporary directory, if necessary). Also one step further on running tbsl from TBSLManager but still changing to be done, for example there seems to be a dependency version maven problem because there is a nosuchmethoderror when calling main from TBSLManager.